# Generated by Django 5.2.3 on 2025-06-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenanceticket', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='unit.unit'),
        ),
    ]
