# Generated by Django. Initial migration for messaging app.
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = []
